name: "Update Configuration and Build"

on:
  workflow_dispatch:
  push:
  delete:

jobs:
  update:
    name: "Update Configuration & Build"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: ubiquity-os/action-deploy-plugin@main
        with:
          action: ${{ github.event_name == 'delete' && 'delete' || 'publish' }}
          sourceRef: ${{ github.event.ref || github.event.workflow_run.head_branch || github.ref_name }}
          artifactPrefix: dist/
          treatAsEsm: true
          sourcemap: false
          pluginEntry: "${{ github.workspace }}/src/action.ts"
          skipBotEvents: false
          excludeSupportedEvents: "issue_comment.created"
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
